apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    editable: true
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200/
    database: 'filebeat-*'
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      esVersion: '7.17.2'
      includeFrozen: false
      maxConcurrentShardRequests: 5
      timeField: '@timestamp'
